layout_spectrum: 0.3011429871930418
typography_spectrum: 0.32266611572852966
color:
  brandStrength: 0.05036827997664119
  lightness: 0.47319174964137667
  saturation: 0.22016598841682594
  rhythmicContrast: 0.13494691312755688
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
github: true
analytics:
  google: UA-103049944-1
author:
  name: Christoph Hautzinger
  email: mail@hautzinger.info
  url: 'https://201created.de'
name: 201created
url: 'https://201created.de'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Projekte
    id: 9458ad1f-7a86-4728-a0dd-94f8bb4f6560
    type: content
  - name: Jobs
    id: bccf6215-c0bb-40d0-ac31-20c52dc9b9b2
    type: content
title: 201created
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/be85b81a-a058-42fc-b71b-e7c017cfd1c8.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/be85b81a-a058-42fc-b71b-e7c017cfd1c8.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Dienstleister für Symfony/React
purpose:
  - type: contact
    url: 'tel:+4917620171547'
    label: Call +4917620171547
