typography_spectrum: 0.7275994203519076
color:
  brandStrength: 0.37397861829958856
  lightness: 0.01740361168049276
  saturation: 0.7350936564616859
  rhythmicContrast: 0.7164835964795202
  brandColors:
    - '#2E0927'
    - '#D90000'
    - '#FF2D00'
    - '#FF8C00'
    - '#04756F'
github: true
layout_spectrum: 0.07029821397736669
analytics:
  google: UA-103049944-1
author:
  name: Christoph Hautzinger
  email: mail@hautzinger.info
  url: 'https://201created.de'
name: 201created
url: 'https://201created.de'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Projekte
    id: 9458ad1f-7a86-4728-a0dd-94f8bb4f6560
    type: content
  - name: Jobs
    id: bccf6215-c0bb-40d0-ac31-20c52dc9b9b2
    type: content
title: 201created
content: []
description: Symfony/React craftmanship
purpose:
  - type: contact
    url: 'tel:+4917620171547'
    label: Call +4917620171547
